version: '3'
services:
  textcraft:
    build: .
    ports:
      - "8000:8000"
      - "7860:7860"
      - "8501:8501"
    network_mode: host
    environment:
      - https_proxy=http://127.0.0.1:7890
      - http_proxy=http://127.0.0.1:7890
      - all_proxy=socks5://127.0.0.1:7890
    env_file:
      - .env
