version: '3'
services:
  textcraft:
    build: .
    container_name: textcraft
    ports:
      - "8000:8000"
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./.env:/usr/src/app/.env
